### ISSUE TITLE
Cast blinding key to byte

### ISSUE THREAD

**Issue by sekulicd** [TDex-network/tdex-daemon#112]
Fix blinding key issue introduced in [here](https://github.com/TDex-network/tdex-daemon/blob/6b4b0fb81a23234bf09fb7ee1d8ae3700472802b/internal/core/application/operator_service.go#L154), where hex encoding of blinding key is added to Observables instead of bytes.

**Comment by altafan** [comment]
Guys can we close this once and for all? Everytime I look at this I think I'm crazy... This is the screenshot of the code


<img width="441" alt="Screen Shot 2020-11-26 at 11 48 48" src="https://user-images.githubusercontent.com/18440657/100341835-655fff00-2fdd-11eb-8939-98be4aedf4c3.png">

`blindingKey` is in hex format, while `blindKey` is a slice of bytes and is just what the observable wants, otherwise we would have had compilation errors for a long time. Things are just ok as they are.

**Comment by tiero** [comment]
@francismars
