### ISSUE TITLE
complete_time_unix of a completed Trade is earlier than accept_time_unix

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#209]
I'm using `tdex-cli@beta` to make trades and with `tdex listswaps` I have the result:

```
{
	"swaps": [
		{
			"status": "COMPLETE",
			"amount_p": "10000000",
			"asset_p": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
			"amount_r": "182272727273",
			"asset_r": "2dd1d5aa89ce9be5656910208aa582ba4f5916491383fdef2832425f313b5290",
			"market_fee": {
				"asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
				"basis_point": "25"
			},
			"request_time_unix": "1605797092",
			"accept_time_unix": "1605797093",
			"complete_time_unix": "1605797092",
			"expiry_time_unix": "1605797212"
		}
	]
}
```﻿

**Comment by sekulicd** [comment]
Here are my findings:

- The issue is that we are wrongly set the value of complete-time, misplacing it with request time, check [here](https://github.com/TDex-network/tdex-daemon/blob/a7aa391bef70eb39eca4a016de0ddecbd6d60b56/internal/interfaces/grpc/handler/operator.go#L409)

- A [method](https://github.com/TDex-network/tdex-daemon/blob/a7aa391bef70eb39eca4a016de0ddecbd6d60b56/internal/core/domain/trade_service.go#L164) which is updating complete time is never used.

@tiero @altafan should we update complete time in blockchain listener by "observing" TransactionConfirmed event?

**Comment by altafan** [comment]
Since a trade can be broadcasted directly by the trader without calling the TradeComplete rpc, we need to start watching for trade transactions to check when they're included in the blockchain. I think that the bc listener, in a similar way to how it takes care of updating the status of the unspents, needs to watch also for transactions of interest (swaps), and when it finds them included in the blockchain, it takes care of updating the Trade by calling its AddBlocktime method.

I remember now that when I added [this](https://github.com/TDex-network/tdex-daemon/blob/a7aa391bef70eb39eca4a016de0ddecbd6d60b56/internal/interfaces/grpc/handler/operator.go#L409), I simply forgot to open a ticket to fix it. At that time we weren't ready yet to watch/update swap transactions. My bad, sorry. 🙏

**Comment by altafan** [comment]
NOTE:
at the moment, the `trade.Complete` method can be used only by the `tradeSvc.TradeComplete` rpc because it expects a partial transaction in base64 format. If a swap is directly broadcasted by the trader, the crawler can trace back to the transaction hex via its hash by making an API call to the explorer's endpoint `/tx/<txID>/hex`.

One option is to change the trade.Complete method so that it expects either a psetBase64 or a txHex. In the first case it just does what it's doing by default right now. In the second case, it should just update just its Status, TxID and TxHex, skipping, in fact, every step related to upset.

What do you think @sekulicd?

**Comment by tiero** [comment]
Am I right that this way we are creating a potential conflicts between the trader interface processing trades and the BC listener try to write into the Trade domain? I know this is not a problem since we retry and also is a very rare occasion, just to be sure I got it right.

**Comment by altafan** [comment]
the bc listener should definitely check that the trade is not already completed before trying to update it.
This cannot cause conflicts because the bc listener will always do its job after TradeComplete, or in place of it in case it's not called by the trader.

**Comment by sekulicd** [comment]
> One option is to change the trade.Complete method so that it expects either a psetBase64 or a txHex. In the first case it just does what it's doing by default right now. In the second case, it should just update just its Status, TxID and TxHex, skipping, in fact, every step related to upset.

As I can see the purpose of trade.Complete method is to validate/extract/finalize and update some fileds, since this(validate/extract/finalize) is already done by the client, I think it is better just to leave this method as is and in blockchain to update these fields using tradeRepo. what do u think?

**Comment by altafan** [comment]
> since this(validate/extract/finalize) is already done by the client

This is not always true. There can also be traders who prefer to let the daemon do such operations by simply signing and sending back the pset to the daemon.

I think we should leave the possibility to the trader to delegate the daemon doing such things. It's a nice to have feature.

**Comment by sekulicd** [comment]
> > since this(validate/extract/finalize) is already done by the client
> 
> This is not always true. There can also be traders who prefer to let the daemon do such operations by simply signing and sending back the pset to the daemon.
> 
> I think we should leave the possibility to the trader to delegate the daemon doing such things. It's a nice to have feature.

I am saying no matter if it is broadcasted by client or by daemon listener should update Status, TxID and TxHex directly using tradeRepo.

**Comment by altafan** [comment]
The fact is that in mainnet, when a tx gets broadcasted, it's not immediately included in the blockchain as it happens in regtest. So basically this 2 moments are the same in regtest, because we mine a block right after a tx is broadcasted, but in mainnet there's a waiting time between these 2 phases.
Hence, if the TradeComplete rpc is called, the trade gets to status completed, and hopefully in the next minute the tx gets included in the blockchain if it has max priority (in mainnet blocks are mined every minute if I'm not wrong).

We cannot allow the bc listener to always set the trade completed for this reason. If it's the daemon that "completes" the trade (broadcasts it) then, mainly for accountability purposes, it has to update the status of the trade.
