### ISSUE TITLE
[Badger] Move unspents to in-memory mode

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#279]
Benefits:

- Lower disk space
- Arguably faster reads and somewhat comparable write times to BadgerDB
- Faster trades and faster Balances RPC response (It could take 14s sometimes!!!)

Cons:

- Increase in RAM/CPU(?) usage
﻿- Slower startup time, but una tantum (recreate the inmemory repo from explorer) 

To do this, we need to reload utxos #299 at daemon startup to recreate the utxo set in-memory (after shutdown or crash)

**Comment by altafan** [comment]
> Increase in RAM/CPU(?) usage
>  ﻿- Slower startup time, but una tantum (recreate the inmemory repo from explorer)

Not sure about this.. What I mean is that at this point we might be interested in storing ONLY the actual unspent whether locked or unlocked.  This would speed up also the restoration: since we already have all the used addresses in storage, it should just be enough to retrieve their unspents, and if done with Esplora in particular, it would return only actual unspent utxos.

Given this, when an unspent is spent we could physically remove it from the storage. At the moment the deletion is logical since we mark those unspents as Spent. This would lead to a smaller utxo set that takes less space on RAM.

There are pros and cons for both logical and physical deletion; this is a nice [SO](https://stackoverflow.com/questions/378331/physical-vs-logical-hard-vs-soft-delete-of-database-record) in which the various answers point out different valid aspects, but it seems to me that in our case the main concern is the impact on memory, so physical deletion might be the preferred choice.
