### ISSUE TITLE
Move db tx management to application level

### ISSUE THREAD

**Issue by altafan** [TDex-network/tdex-daemon#305]
Currently, the operation of trying to commit a db transaction is delegated to the grpc handlers.
So basically we put an high-level component like a grpc handler (that should be responsible just to translate data coming from a lower level into a specific format like protobuf, json, etc.) in charge of doing a low-level operation like re-trying to commit a db tx if it caused a conflict.

Everything related to storage management should live in the application layer. So, as the title suggests, these kind of operations should be moved at application level. This would make it possible to write component tests to validate the behavior of the app in case of concurrent requests.

**Comment by tiero** [comment]
Pull in @sekulicd

**Comment by sekulicd** [comment]
History of related issues(maybe i missed some): 
Issue #145 - Create a dedicate badger db instance for Unspents (PR #155)
Issue #139 - [Badger] Create dedicated db instance for Prices (PR #156)
Issue #115 - Stream rpc send replies before the db transaction is committed (PR #177)
Issue #303 - TradeComplete: respond ASAP to clients and update Trades repo in async (#304)

Context:
Initial goal was to have 'transactional' application services and that core is not aware of store management.
I wanted to have unified solution so that we are handling transaction creation and commit in one place.
The most elegant way, IMHO, was to do this was in interceptor, we create tx, pass it down in context, and commit after handler returns successful response. 
Benefits of this idea was:
1. Unified solution, one place to handle this sensitive task
2. This way core was unaware of infra part that was handling storage.
3. Transactional application services methods

Then we found out about transaction conflicts that are not handled(retried) by badger internally. 
We splitted DB so we have separate Badger Stores for(Issue #145, Issue #139):
1. for unspents
2. for markets, vault, trades, and unspent locks
3. for prices
Also we add retry of transaction in interceptor.
After we did this we found out that retrying transaction is not good enough for Stream RPC's, so we moved retry mechanism in GRPC handler layer.(Issue #115)
Recently issue arised with response time to the client (Issue #303)

Requirements:
1. Consistency/Reliability
2. Responsivness
3. Clean solution
 Key requirement that we want to satisfy is to have consistante data in DB, which means we need to implement retry mechanisam.
 I guess that responsivnes is second most important requirement and we want to have unified/clean/elegant solution as much as possible.
 
 I suggest as follows:
 1. Have one Badger Store for all repositories (we cant have transaction across multiple stores)
 2. All repository methods should work with passed tx in context or handle tx retry by itself
 3. For unary calls handle tx in interceptor
 4. For stream calls handle tx like currently(in GRPC handlers) but run [runTransaction](https://github.com/TDex-network/tdex-daemon/blob/0adcc0c066a5dce1b4d198d4fe31ba7d0cc2963f/internal/infrastructure/storage/db/badger/db_manager.go#L77) in separate go routine so user doesnt needs to wait

**Comment by tiero** [comment]
I have a write-up coming about it. It seems something that needs more time to be analyzed and discussed and will not go inside in this release ofc.

#304 altough suboptimal and potentially a "polluter", has a greater impact on business operations right away and allows tdex clients to interact with a daemon that can accept trades (currently 80% of trades do not go through due conflicts errors at the TradeComplete)

**Comment by sekulicd** [comment]
Another option to consider(maybe not so good option) is to lock transaction when created.
https://github.com/dgraph-io/badger/issues/742

**Comment by altafan** [comment]
I want to point out, tho, that layers above the application one shouldn't be aware or in charge of handling storage(s) because lifting such tasks a layer up, implies that every kind of interface that's gonna be implemented in the future will need to do the same. And in general, the layer above the application one should be presentational in our design, therefore there isn't that separation of concerns we wanted to achieve at the moment.

I do believe that #304 is a good starting point to make things cleaner than they are ATM.
Waiting for the write-up to keep debating on this.
