### ISSUE TITLE
[tdex] auto create a state.json with defaults in the datadir. config init command should be able to overwrite 

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#341]

**Comment by altafan** [comment]
This is something for sure useful when using default datadirs, but what if the user wants to use a custom datadir for his cli by exporting the TDEX_OPERATOR_DATADIR env?

**Comment by tiero** [comment]
It will eventually use `tdex config set` to change it

**Comment by altafan** [comment]
I didn't get how this could solve the problem I pointed out, I woud like to have these open question answered:
- Who creates the JSON state file? (I supposed it's the daemon)
- When the file is created? (I supposed at daemon's startup)
- Where he/she/it creates the file? (I supposed in the default TDEX_OPERATOR_DATADIR which is not part of the daemon scope and env vars) 
- What if the user wants to use a custom datadir instead of the default one? How the file could be created in that path instead of the default one? (this last point could be clarified by the those preceiding actually)

**Comment by tiero** [comment]
I refer to tdex cli ONLY. Ie. The first time user runs whatever command (ie. In the go func init() ?) we go check if state.json is in the default datadir, if not we automatically create it with the defaults. 

We should still retain the tdex config init, as a way to set many keys at once, without doing manyn `tdex config set`


To change the path we should use either a CLI ENV VAR or maybe just global level flag --datadir 

`tdex --config my/custom/path <command> <subcommand>

**Comment by tiero** [comment]
No, its not related the daemon. The CLI can be used remotely on a different machine of the daemon.

Its just the default should go look to AppDataDir, since the most common scenario is tdexd and tdex on same machine/container.

**Comment by altafan** [comment]
> Its just the default should go look to /.tdex-daemon in AppDataDir for tls/macaroon paths, since the most common scenario is tdexd and tdex on same machine/container.

Yeah, this is the default scenario after the last commit.

> I refer to tdex cli ONLY. Ie. The first time user runs whatever command (ie. In the go func init() ?) we go check if state.json is in the default datadir, if not we automatically create it with the defaults.
>
> We should still retain the tdex config init, as a way to set many keys at once, without doing manyn tdex config set
>
> To change the path of default `tdex-operator` folder we should use either a CLI ENV VAR or maybe just global level flag --config to point for state.json file
>
> `tdex --config my/custom/path <command> <subcommand>`

Thanks for the clarification 👍 . The `--config` flag is the bitcoin-cli approach (the flag is just called differently `--datadir`).
I think the env var apporach is more confortable than the flag one because with the latter you have to always remeber to put the flag for every command you want to execute.

**Comment by tiero** [comment]
I would put both NEV and --config/--datadir flag just in case :)
