### ISSUE TITLE
Support detecting swaps settlement made with non-segwit wallets

### ISSUE THREAD

**Issue by nicofuccella** [TDex-network/tdex-daemon#369]
After the first trade, the deamon quote asset balance becomes zero.
Steps I followed:
- initialize the deamon with 100000000 units of the minted coin
- made a trade in order to buy 45000000 units
- call the `Balances` gRPC rpc
Here the response:
```json
{
  "balances": [
    {
      "balance": {
        "base_amount": "100000000",
        "quote_amount": "0"
      },
      "fee": {
        "basis_point": "25",
        "fixed": null
      }
    }
  ]
}
```
Obviously all the subsequent trade propose calls are failing. I also checked the minted coin balance of the client and it actually contains only 45000000 units.

**Comment by tiero** [comment]
can you attach the logs of tdexd? if you running in docker `docker logs tdexd`

**Comment by altafan** [comment]
The problem with balances should be just a matter of time. As I presume, if you created a market with just one utxo per asset pair, then you have to wait until either the trade gets settled or expires.

After an offline conversation, though, it came up that the trade has been done by the trader using wrapped segwit (p2sh-p2pwpkh) addresses and this led us to discover a bug in the daemon. A detailed description follows:

In TradePropose, after a trade has been accepted, the daemon starts watching for what it thinks the trade tx hash will be. Until this moment we have always tested trades made of native segwit inputs and the behavior of the daemon has always been correct. This because the signature(s) added later by the trader are serialized as part of the input witness, therefore the tx hash never changes from "unsigned" to "signed".

Unfortunately, this doesn't apply when using wrapped segwit or legacy inputs. Better to remember that for the former, the `scriptSig` must contain the wrapped native segiwt script (p2wpkh in our case so to speak), while for the latter the script contains the actual signature, making the trade tx hash not predictable at all.

The daemon needs another strategy to check the status of a trade when "scanning" the blockchain. Instead of looking for trade transaction ids, it should look for the status of the outpoints used as inputs of those trades. Detailed information about this will follow in another issue.
