### ISSUE TITLE
permissions guard prevent calling  Wallet Unlocker

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#578]
With master 

```
[tdex] rpc error: code = Unknown desc = /tdex.daemon.v1.WalletUnlocker/GenSeed: unknown permissions required for method
```

**Comment by altafan** [comment]
Ok, the problem here is not actually with the permission logic and the tests, but rather is that we hardcoded the service names for every method full path, like for example, `WalletUnlocker` [here](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/permissions/permissions.go#L164).

It should be enough to source the services' names from the proto (just like @sekulicd did in his #581 already) instead of having them hardcoded.
