### ISSUE TITLE
Cannot change password if wallet not locked

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#602]
When adding a change password form on Tdex dashboard using `ChangePasswordRequest` I realize that it's currently not possible. I get error `wallet must be locked to perform this operation`. 
Imo it should be possible to change the password even when not locked.
Or we could lock and unlock just the time of the operation but we are missing a `Lock` rpc. 

@tiero @altafan @sekulicd

**Comment by altafan** [comment]
By design, you can't change the password of an unlocked daemon. You need to lock it, change the password and then unlock it again in order to update the encrypted mnemonic stored on the disk.
ATM, the only way to lock a daemon is by restarting it therefore I can see that changing the password of an unlocked daemon from the dashboard it's for sure tricky.

Soon, though, we will add a Lock() rpc on the WalletUnlocker service to facilitate this kind of operation without the need of restarting the daemon manually

PS: Pardon for the late reply.
