### ISSUE TITLE
tdex cli: config connect does not support proto=http

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#643]
I tried to pass `tdexdconnect://localhost:9000?proto=http` as connect url to `tdex config connect` command, but 
then calling `tdex status` still returns an error that is looking for a TLS certificate

```sh
tdex status
[tdex] could not read TLS certificate:  open : no such file or directory
exit status 1
```

## Workaround

`tdex config set no_tls true`

**Comment by altafan** [comment]
It's very likely that we forgot to update the CLI once we added the proto to the connect URL, therefore it just ignores the proto specified in the connect url

**Comment by altafan** [comment]
After checking the code, I found that we already [handle and store](https://github.com/tdex-network/tdex-daemon/blob/master/cmd/tdex/config.go#L200-L208) `proto` in cli's state, but we miss to check it when [creating the connection](https://github.com/tdex-network/tdex-daemon/blob/2f51e824825b1730901606bc93a7b87d1277ba20/cmd/tdex/main.go#L280-L297) to the daemon.

The correct behavior should be checking if proto is `https`  when `noTls` is true and append a `credential.NewTls(nil))` to the transport credentials just in case, otherwise we keep appending insecure creds.

**Comment by tiero** [comment]
> we already [handle and store](https://github.com/tdex-network/tdex-daemon/blob/master/cmd/tdex/config.go#L200-L208) proto in cli's state

Shouldnt we set `no_tls` then?

**Comment by tiero** [comment]
> The correct behavior should be checking if proto is https when noTls is true and append a credential.NewTls(nil)) 

I am in favor of 

- no_tls = true > calls in http
- no_tls = false & tls_cert_path IS EMPTY > calls in https 
- no_tls = false & tls_cert_path NOT EMPTY > calls in https with cert
