### ISSUE TITLE
[InitWallet] macaroon is not always returned

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#646]
Macaroon is not always returned in stream responses of InitWallet().

Successful call
<img width="1032" alt="Screenshot 2022-10-04 at 15 11 36" src="https://user-images.githubusercontent.com/4022128/193829162-d7bdf4ac-8f41-4f45-b528-5d78c5fe2983.png">

Unsuccessful call
<img width="1026" alt="Screenshot 2022-10-04 at 15 00 26" src="https://user-images.githubusercontent.com/4022128/193829140-d01ce5ab-edb7-479c-92f9-d60c9076ac61.png">

Steps to replicate:
- Run daemon (without TLS for simplicity)
```
docker run -it -d --name tdexd \
  -p 9945:9945 -p 9000:9000 \
  -v "$(pwd)/tdexd:/home/user/.tdex-daemon" \
  -e TDEX_NO_MACAROONS=false \
  -e TDEX_CONNECT_PROTO=http \
  -e TDEX_NO_OPERATOR_TLS=true \
  -e TDEX_NETWORK="regtest" \
  -e TDEX_BASE_ASSET="$TDEX_BASE_ASSET" \
  -e TDEX_LOG_LEVEL=5 \
  -e TDEX_EXPLORER_ENDPOINT="http://chopsticks-liquid:3000" \
  --network="nigiri" \
  ghcr.io/tdex-network/tdexd:latest
```

Call on Bloom
```
{
  "wallet_password": "aaaaaaaa",
  "seed_mnemonic": [
    "length", 
    "march", 
    "alarm", 
    "eagle", 
    "recycle", 
    "few", 
    "more", 
    "denial", 
    "canyon", 
    "physical", 
    "meadow", 
    "wish", 
    "ball", 
    "coil", 
    "copper", 
    "cry", 
    "honey", 
    "then", 
    "rigid", 
    "mind", 
    "misery", 
    "access", 
    "melt", 
    "obvious"
  ],
  "restore": false
}
```

Stop daemon and rerun 5 or 10 times until you encounter the bug that happens randomly.

**Comment by altafan** [comment]
@sekulicd can you investigate on this?

**Comment by sekulicd** [comment]
> @sekulicd can you investigate on this?

Sure

**Comment by sekulicd** [comment]
Here is outcome of my investigation.

I managed to reproduce the issue(I was using CLI instead of Bloom).

1.  Run daemon with Stephane's above cmd
2. Call InitWallet func using CLI
3. See result and run "cleaning" script:
````
#!/bin/bash

set -e

docker stop lokaldi
docker rm lokaldi
rm -rf ./tdexd
````
After repeating this few time(+5) in terminal i can see bellow:
````
create wallet STATUS_PROCESSING
create wallet STATUS_DONE
admin.macaroon
````
From the above and by analysing code i concluded that wallet was created(initialised) and that code went through [this](https://github.com/tdex-network/tdex-daemon/blob/8eb589c6bbce2049e4aa045c866f8e15601f287c/internal/interfaces/grpc/handler/walletunlocker.go#L121) loop read file that is created but since file still not populated it read no bytes and returned empty string to the client.

In order to debug I tried to reproduce the same by starting/stopping/cleaning daemon locally from IDE but didnt managed to reproduce.
Then i added debug logs(at places before and after writing/reading to/from file), build image locally and try but with that img issue was not happening.

Whats left is to try understanding the issue only by watching code base, and i think that this is race issue of writing/reading to the admin.macaroons file from two go routines(writing in [here](https://github.com/tdex-network/tdex-daemon/blob/8eb589c6bbce2049e4aa045c866f8e15601f287c/internal/interfaces/grpc/service.go#L504) and reading in [here](https://github.com/tdex-network/tdex-daemon/blob/8eb589c6bbce2049e4aa045c866f8e15601f287c/internal/interfaces/grpc/handler/walletunlocker.go#L126))

One idea that could potentially fix this is adding check [before break](https://github.com/tdex-network/tdex-daemon/blob/8eb589c6bbce2049e4aa045c866f8e15601f287c/internal/interfaces/grpc/handler/walletunlocker.go#L133)
````
if len(mac) == 0 {
	continue
}
````

@tiero @altafan @Janaka-Steph

**Comment by altafan** [comment]
Thanks @sekulicd.

I think your proposal makes totally sense, but I want to add another consideration: what if [here](https://github.com/tdex-network/tdex-daemon/blob/8eb589c6bbce2049e4aa045c866f8e15601f287c/internal/interfaces/grpc/handler/walletunlocker.go#L126) we check only for file existence instead of reading directly from it? Maybe this could solve this allegied race condition, but i would still add the check you suggested to be 100% sure to not return an empty macaroon.
