### ISSUE TITLE
[Feature Request] ListWebhook - Add an ActionType to retrieve all hooks  

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#666]
ACTION_TYPE_ALL_ACTIONS doesn't return all types. It only returns hooks set with action Any.
It would be nice to be able to retrieve hooks of all possible types with a single request.

Also renaming ACTION_TYPE_ALL_ACTIONS to ACTION_TYPE_ANY_ACTIONS

**Comment by altafan** [comment]
I don't think it's necessary to add a new action type to retrieve all hooks, and it doesn't make really sense either IMO because we want to list all webhooks regardless their action.

Rather, we can either add a new RPC ListAllWebhooks or add a new boolean field `all` to the ListWebhookRequest message.

**Comment by altafan** [comment]
cc @tiero

**Comment by tiero** [comment]
> add a new RPC ListAllWebhooks

this seems the way to go
